const now = new Date()

export default [
  {
    id: 0,
    title: 'Estudo de Matemática',
    discipline: 'Matemática',
    tasks: ['Estudar geometria', 'Funções'],
    allDay: true,
    start: new Date(2023, 4, 5),
    end: new Date(2023, 4, 6),
  },
  {
    id: 1,
    title: 'Estudo de Física',
    discipline: 'Física',
    tasks: ['Estudar mecânica', 'Eletricidade e Magnetismo'],
    start: new Date(2023, 4, 10),
    end: new Date(2023, 4, 13),
  },
  {
    id: 2,
    title: 'Estudo de Química',
    discipline: 'Química',
    tasks: ['Estudar tabela periódica', 'Ligações Químicas'],
    start: new Date(2023, 4, 18),
    end: new Date(2023, 4, 25),
  },
  {
    id: 3,
    title: 'Estudo de Biologia',
    discipline: 'Biologia',
    tasks: ['Estudar células', 'Sistema Digestivo'],
    start: new Date(2023, 5, 3),
    end: new Date(2023, 5, 10),
  },
  {
    id: 4,
    title: 'Estudo de Português',
    discipline: 'Português',
    tasks: ['Estudar gramática', 'Análise de textos literários'],
    start: new Date(2023, 5, 11),
    end: new Date(2023, 5, 12),
  },
  {
    id: 5,
    title: 'Estudo de Inglês',
    discipline: 'Inglês',
    tasks: ['Estudar gramática', 'Prática de conversação'],
    start: new Date(2023, 5, 15),
    end: new Date(2023, 5, 17),
    desc: 'Big conference for important people',
  },
  {
    id: 14,
    title: 'Estudo de História',
    discipline: 'História',
    tasks: ['Estudar História Antiga', 'História Moderna'],
    start: new Date(2023, 5, 20),
    end: new Date(2023, 5, 22),
  },
  {
    id: 15,
    title: 'Estudo de Geografia',
    discipline: 'Geografia',
    tasks: ['Estudar Geografia Física', 'Geografia Humana'],
    start: now,
    end: now,
  },
]
